import { Diagram, MindNode, MindEdge } from '../types';

export const INITIAL_DIAGRAMS: Diagram[] = [
  {
    id: 'mindmap-tech-startup',
    title: 'Tech Startup Launch Plan 2026',
    description: 'Comprehensive mind map covering core stages of building and scaling a technology product.',
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now(),
    gridStyle: 'dots',
    defaultLineStyle: 'curved',
    viewport: { x: 120, y: 160, zoom: 0.95 },
    nodes: [
      {
        id: 'node-root',
        title: '🚀 Tech Startup 2026',
        note: 'Core mission, vision, and strategic goals. Target Product-Market Fit in first 6 months.',
        x: 400,
        y: 300,
        width: 230,
        height: 80,
        color: '#19B5FE',
        bgColor: '#FFFFFF',
        shape: 'rounded',
        isRoot: true,
        priority: 'high',
        status: 'in_progress',
        tags: ['Strategy', 'Startup'],
        fontWeight: 'bold',
      },
      // Branch 1: Product Development
      {
        id: 'node-product',
        title: '📦 Product Development',
        note: 'UX/UI design workflow, MVP build, and intelligent AI features.',
        x: 750,
        y: 120,
        width: 210,
        height: 68,
        color: '#19B5FE',
        bgColor: '#FFFFFF',
        shape: 'rounded',
        parentId: 'node-root',
        priority: 'high',
        status: 'in_progress',
        tags: ['Product', 'MVP'],
      },
      {
        id: 'node-mvp',
        title: '⚡ Build Core MVP',
        note: 'Streamlined version solving the highest priority customer pain point.',
        x: 1060,
        y: 60,
        width: 190,
        height: 60,
        color: '#19B5FE',
        shape: 'rounded',
        parentId: 'node-product',
        priority: 'high',
        status: 'done',
        tags: ['V1.0', 'Core Feature'],
      },
      {
        id: 'node-ux',
        title: '🎨 Node UI & UX System',
        note: 'Smooth drag-and-drop experience, refined white tone & #19B5FE aesthetic.',
        x: 1060,
        y: 140,
        width: 200,
        height: 60,
        color: '#19B5FE',
        shape: 'rounded',
        parentId: 'node-product',
        priority: 'medium',
        status: 'in_progress',
        tags: ['Figma', 'Design System'],
      },
      {
        id: 'node-ai',
        title: '🤖 AI & Automation Layer',
        note: 'Smart synthesis and productivity enhancements with Gemini models.',
        x: 1060,
        y: 220,
        width: 210,
        height: 60,
        color: '#0284C7',
        shape: 'rounded',
        parentId: 'node-product',
        priority: 'medium',
        status: 'todo',
        tags: ['AI Agent', 'API'],
      },

      // Branch 2: Marketing & Growth
      {
        id: 'node-marketing',
        title: '📈 Marketing & Growth',
        note: 'Multi-channel acquisition strategy targeting first 10,000 active users.',
        x: 750,
        y: 350,
        width: 210,
        height: 68,
        color: '#0284C7',
        bgColor: '#FFFFFF',
        shape: 'rounded',
        parentId: 'node-root',
        priority: 'medium',
        status: 'in_progress',
        tags: ['Growth', 'Go-to-market'],
      },
      {
        id: 'node-content',
        title: '✍️ Content & SEO Engine',
        note: 'High-value technical articles and real-world case studies.',
        x: 1060,
        y: 310,
        width: 200,
        height: 60,
        color: '#0284C7',
        shape: 'rounded',
        parentId: 'node-marketing',
        tags: ['SEO', 'Blog'],
      },
      {
        id: 'node-community',
        title: '🌐 Community Hub',
        note: 'Discord server, GitHub discussions, and direct feedback channel.',
        x: 1060,
        y: 390,
        width: 190,
        height: 60,
        color: '#0284C7',
        shape: 'rounded',
        parentId: 'node-marketing',
        tags: ['Community', 'Discord'],
      },

      // Branch 3: Operations & Finance
      {
        id: 'node-ops',
        title: '💰 Finance & Operations',
        note: 'Seed / Angel fundraising, compliance, and cash-flow management.',
        x: 60,
        y: 160,
        width: 200,
        height: 68,
        color: '#10B981',
        bgColor: '#FFFFFF',
        shape: 'rounded',
        parentId: 'node-root',
        priority: 'high',
        status: 'in_progress',
        tags: ['Finance', 'Legal'],
      },
      {
        id: 'node-runway',
        title: '📊 18-Month Runway',
        note: 'Conservative budget buffer for infrastructure and key hires.',
        x: -220,
        y: 130,
        width: 210,
        height: 60,
        color: '#10B981',
        shape: 'rounded',
        parentId: 'node-ops',
        tags: ['Budget'],
      },
      {
        id: 'node-pitch',
        title: '📑 Investor Pitch Deck',
        note: 'Concise 10-slide presentation highlighting traction and vision.',
        x: -220,
        y: 210,
        width: 200,
        height: 60,
        color: '#10B981',
        shape: 'rounded',
        parentId: 'node-ops',
        tags: ['Seed', 'Deck'],
      },

      // Branch 4: Team & Culture
      {
        id: 'node-team',
        title: '👥 Team & Culture',
        note: 'Recruiting lead engineers and fostering an ownership culture.',
        x: 60,
        y: 400,
        width: 200,
        height: 68,
        color: '#8B5CF6',
        bgColor: '#FFFFFF',
        shape: 'rounded',
        parentId: 'node-root',
        priority: 'medium',
        status: 'todo',
        tags: ['HR', 'Culture'],
      },
      {
        id: 'node-dev',
        title: '💻 Full-Stack Engineer',
        note: 'Strong proficiency in React, TypeScript, canvas graphics, and API integration.',
        x: -220,
        y: 380,
        width: 190,
        height: 60,
        color: '#8B5CF6',
        shape: 'rounded',
        parentId: 'node-team',
        tags: ['Dev', 'Hiring'],
      },
      {
        id: 'node-culture',
        title: '🌱 Ownership & Autonomy',
        note: 'Focus on measurable outcomes and high-trust delegation.',
        x: -220,
        y: 460,
        width: 210,
        height: 60,
        color: '#8B5CF6',
        shape: 'rounded',
        parentId: 'node-team',
        tags: ['Culture'],
      }
    ],
    edges: [
      { id: 'e-root-prod', fromNodeId: 'node-root', toNodeId: 'node-product', color: '#19B5FE', style: 'curved' },
      { id: 'e-prod-mvp', fromNodeId: 'node-product', toNodeId: 'node-mvp', color: '#19B5FE', style: 'curved' },
      { id: 'e-prod-ux', fromNodeId: 'node-product', toNodeId: 'node-ux', color: '#19B5FE', style: 'curved' },
      { id: 'e-prod-ai', fromNodeId: 'node-product', toNodeId: 'node-ai', color: '#0284C7', style: 'curved' },

      { id: 'e-root-mkt', fromNodeId: 'node-root', toNodeId: 'node-marketing', color: '#0284C7', style: 'curved' },
      { id: 'e-mkt-cnt', fromNodeId: 'node-marketing', toNodeId: 'node-content', color: '#0284C7', style: 'curved' },
      { id: 'e-mkt-com', fromNodeId: 'node-marketing', toNodeId: 'node-community', color: '#0284C7', style: 'curved' },

      { id: 'e-root-ops', fromNodeId: 'node-root', toNodeId: 'node-ops', color: '#10B981', style: 'curved' },
      { id: 'e-ops-run', fromNodeId: 'node-ops', toNodeId: 'node-runway', color: '#10B981', style: 'curved' },
      { id: 'e-ops-pit', fromNodeId: 'node-ops', toNodeId: 'node-pitch', color: '#10B981', style: 'curved' },

      { id: 'e-root-team', fromNodeId: 'node-root', toNodeId: 'node-team', color: '#8B5CF6', style: 'curved' },
      { id: 'e-team-dev', fromNodeId: 'node-team', toNodeId: 'node-dev', color: '#8B5CF6', style: 'curved' },
      { id: 'e-team-cul', fromNodeId: 'node-team', toNodeId: 'node-culture', color: '#8B5CF6', style: 'curved' },
    ]
  },
  {
    id: 'mindmap-learning-ai',
    title: 'Frontend & AI Learning Roadmap 2026',
    description: 'Structured roadmap from modern UI fundamentals to production LLM and agent workflows.',
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now(),
    gridStyle: 'dots',
    defaultLineStyle: 'curved',
    viewport: { x: 100, y: 150, zoom: 1 },
    nodes: [
      {
        id: 'ai-root',
        title: '🧠 Modern Frontend + AI',
        note: 'Comprehensive 6-month roadmap mastering modern web interfaces and AI APIs.',
        x: 350,
        y: 280,
        width: 230,
        height: 76,
        color: '#19B5FE',
        shape: 'rounded',
        isRoot: true,
        priority: 'high',
        status: 'in_progress',
        tags: ['Learning', '2026'],
      },
      {
        id: 'ai-fe',
        title: '⚛️ Modern Frontend Architecture',
        note: 'React 19, TypeScript 5+, Tailwind CSS, and scalable component hierarchies.',
        x: 680,
        y: 180,
        width: 200,
        height: 64,
        color: '#19B5FE',
        parentId: 'ai-root',
        status: 'done',
        tags: ['React', 'TypeScript'],
      },
      {
        id: 'ai-sdk',
        title: '⚡ Gemini & LLM SDKs',
        note: 'Google Gen AI SDK integration, multimodal prompts, and streaming responses.',
        x: 680,
        y: 360,
        width: 210,
        height: 64,
        color: '#19B5FE',
        parentId: 'ai-root',
        status: 'in_progress',
        tags: ['Gemini', 'SDK'],
      },
      {
        id: 'ai-agents',
        title: '🛠️ AI Agents & Function Calling',
        note: 'Tool orchestration, structured output parsing, and automated pipelines.',
        x: 980,
        y: 360,
        width: 220,
        height: 64,
        color: '#0284C7',
        parentId: 'ai-sdk',
        status: 'todo',
        tags: ['Agent', 'Automation'],
      }
    ],
    edges: [
      { id: 'e-ai-1', fromNodeId: 'ai-root', toNodeId: 'ai-fe', color: '#19B5FE', style: 'curved' },
      { id: 'e-ai-2', fromNodeId: 'ai-root', toNodeId: 'ai-sdk', color: '#19B5FE', style: 'curved' },
      { id: 'e-ai-3', fromNodeId: 'ai-sdk', toNodeId: 'ai-agents', color: '#0284C7', style: 'curved' },
    ]
  }
];
